### ISSUE TITLE
Error: secret option required for sessions

### ISSUE THREAD

**Issue by Warredfre** [shitcorp/discord-bot-dashboard#99] opened 2020-04-02 17:06 UTC
Hello ! First of all thank you for creating this dashboard!

However I have an error, when I go to the web page it tells me this:

`Error: secret option required for sessions
    at session (D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\express-session\index.js:200:12)
    at Layer.handle [as handle_request] (D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\express\lib\router\index.js:317:13)
    at D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\express\lib\router\index.js:275:10)
    at SessionStrategy.strategy.pass (D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\passport\lib\middleware\authenticate.js:343:9)
    at SessionStrategy.authenticate (D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\passport\lib\strategies\session.js:75:10)
    at attempt (D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\passport\lib\middleware\authenticate.js:366:16)
    at authenticate (D:\Thomas\Documents\discord-bot-dashboard-master\node_modules\passport\lib\middleware\authenticate.js:367:7)
`

Thank you in advance for your help !

**Comment by Warredfre** [comment] 2020-04-02 17:08
So I wonder where to get the code for "SESSION_SECRET"

**Comment by Warredfre** [comment] 2020-04-02 20:10
You can Close This
Thx

**Comment by julianYaman** [comment] 2020-07-06 20:41
Hello, the issue is now fixed in the newest development version of the dashboard. 
This issue will be closed after the `the-epic-gamer-branch` will be merged to the `master` branch.

**Comment by Huskydog9988** [comment] 2022-02-11 22:56
The project has comepletly changed its codease and this is no longer valid.

**Closed by Huskydog9988** 2022-02-11 22:56 UTC
Labels: bug, closed when merged to master
